### ISSUE TITLE
Unable to use inline functions in projects which are build with JVM target 1.8

### ISSUE THREAD

**Issue by jadar** [sebaslogen/resaca#117]
The default version of the JVM in Kotlin project seems to be 1.8. [source](https://kotlinlang.org/docs/gradle-compiler-options.html#attributes-specific-to-jvm) When I try to use the `resacakoin` module, I am unable to call inline functions because the project targets 17, not 1.8. I am hesitant to move my JVM target only in order to use this module. Is there a workaround for this?

**Comment by sebaslogen** [comment]
Hi, 
The only two options AFAIK are either upgrading your project to java 17 or downgrading resaca to java 1.8
To be honest I used java 17 because it was the default for modern projects back when I created the library. This means that through desugaring the Android toolchain can make sure that the code will run as optimized as possible on the target Android OS, even if it's an older version of Android, and new versions of Android will benefit from using more modern Java bytecode from version 17.
If you have a good use case that requires using a 10 years old version of Java I'm totally open to target 1.8 and let go of the Java bytecode optimizations, I don't expect a performance impact with the amount of times this library gets called in recompositions.

**Comment by jadar** [comment]
I don't have a specific use case for using 1.8. I think 1.8 was the default when I created my Kotlin project, and the docs show that 1.8 is the default in the Kotlin Gradle plugin, so I assume that's what a lot of other projects were using. I haven't tried updating to 17, but that could be an option.

**Comment by sebaslogen** [comment]
Then I suggest you migrate to java 17 and jdk 17.
Also the Android Gradle Plugin requires a minimum of jdk 17 to run since a few months already: https://developer.android.com/build/releases/gradle-plugin#compatibility

**Comment by sebaslogen** [comment]
As discussed, I'm closing this issue until there is a need to actually support Java 1.8 for a specific use case, in that case feel free to re-open this issue or mention it in a new one.

Thanks for the healthy discussion.
