### ISSUE TITLE
Koin is not supported

### ISSUE THREAD

**Issue by OKatrych** [sebaslogen/resaca#6]
When trying to use the `viewModelScoped` with Koin's `koinInject()` the compilation throws the error: "Composable calls are not allowed inside the builder". 
Please note that `koinInject()` is a `@Composable` function and it's usage is not allowed inside the non-composable `noinline builder: @DisallowComposableCalls () -> T`.

Example:
```
@Composable
@Preview
private fun DialogContent(
    modifier: Modifier = Modifier,
    viewModel: SubscriptionViewModel = viewModelScoped { koinInject() }, // Error
)
```

**Comment by sebaslogen** [comment]
Have you tried with the `get()` function from Koin?

https://insert-koin.io/docs/reference/koin-android/get-instances/

I assume the one you mentioned `koinInject()` tries to automatically manage the lifecycle of your view model through the composable. Since you're using resaca to handle the lifecycle of the view model, the Koin library doesn't need to take that responsibility anymore.

**Comment by OKatrych** [comment]
My bad, totally forgot that this can be got from the activity.

**Comment by sebaslogen** [comment]
No problem, I'm glad it worked 🙂

**Comment by sebaslogen** [comment]
FYI: I have just added more documentation and examples on how to use resaca with Koin, plus a new extension library to support ViewModels with SavedStateHandle using Koin and resaca https://github.com/sebaslogen/resaca/blob/main/resacakoin/Readme.md

**Comment by OKatrych** [comment]
@sebaslogen this is 🥇. Thank you a lot 🙂.
